### PR TITLE
feat(parser): implement pattern matching

### PR DESCRIPTION
**Pull request by teran-joseluis**
## Description

I worked on some parser functions for **Pattern Matching**, also I added a resource which is our **EBNF** for the Yamil Language to review it during the developing process.

## Type of Change

Put an `x` in all the boxes that apply:

- [x] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

Put an `x` in all the boxes that apply:

- [x] My commit messages are detailed.
- [x] My code follows the code style of this project.
- [x] No existing features have been broken without good reason.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by teran-joseluis** [comment]
It is important to mention that I have reopened my **PR** about **Pattern Matching** feature due to an observation made by my partners about the quantity of commits in the previous [**PR - 11**](https://github.com/Programming-Languages-I/yamil-language/pull/11). Additionally, I merged commented code into the develop branch, which was not correct.  So, I have removed that code from the **develop** branch and now I'm waiting for approval again for it to be merged.

**Comment by teran-joseluis** [comment]
Also, I forgot to mention here.

While performing unit tests for my feature in the previous [PR - 11](https://github.com/Programming-Languages-I/yamil-language/pull/11), I discovered a bug in `parseLiteral` function. This issue forced me to comment out the unit tests I had written. As I reopen this **PR**, the commented code remains in its current state because the bug has not yet been fixed. I have opened a separate [**PR - 15**](https://github.com/Programming-Languages-I/yamil-language/pull/15) to address this bug, which is currently under code review. Once it is approved, I will uncomment those unit tests.

**Comment by teran-joseluis** [comment]
Also, I forgot to mention here.

While performing unit tests for my feature in the previous [**PR - 11**](https://github.com/Programming-Languages-I/yamil-language/pull/11), I discovered a bug in `parseLiteral` function. This issue forced me to comment out the unit tests I had written. As I reopen this **PR**, the commented code remains in its current state because the bug has not yet been fixed. I have opened a separate [**PR - 15**](https://github.com/Programming-Languages-I/yamil-language/pull/15) to address this bug, which is currently under code review. Once it is approved, I will uncomment those unit tests.

**Comment by teran-joseluis** [comment]
Also, I forgot to mention here.

While performing unit tests for my feature in the previous [**PR - 11**](https://github.com/Programming-Languages-I/yamil-language/pull/11), I discovered a bug in `parseLiteral` function. This issue forced me to comment out the unit tests I had written. As I reopen this **PR**, the commented code remains in its current state because the bug has not yet been fixed. I have opened a separate [**PR - 18**](https://github.com/Programming-Languages-I/yamil-language/pull/18) to address this bug, which is currently under code review. Once it is approved, I will uncomment those unit tests.

**Review by fabianromeroclaros — APPROVED** [review]

**Review by JosuePrado — APPROVED** [review]

**Pull request merged**
